--CREATING WORDS TABLE
CREATE TABLE WORDS (	
   PK_ID NUMBER(*,0), 
   WORD VARCHAR2(255 BYTE),
   GRADE VARCHAR2(20 BYTE)
) ;
--DROPPING WORDS TABLE IF NEEDED  
DROP TABLE WORDS;

--CREATING DICTIONARY TABLE
CREATE TABLE DICTIONARY(
     PART_OF_SPEECH VARCHAR2(255 BYTE), 
     DEFINITION VARCHAR2(255 BYTE), 
     WORD_USAGE VARCHAR2(255 BYTE), 
     FK_ID NUMBER(*,0)
) ;

--DROPPING DICTIONARY TABLE IF NEEDED  
DROP TABLE DICTIONARY;

--Creating Sequence Numbers
--This sequence number is for the auto-incrementing primary key then inserting new rows into the table.
--CREATING WORDS SEQUENCE NUMBER
 CREATE SEQUENCE ID_PRI_WORDS
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE 
  CACHE 20
  NOORDER;
--DROPPING WORDS SEQUENCE NUMBER IF NEEDED  
DROP SEQUENCE ID_PRI_WORDS; 


-Creating Triggers
--CREATING WORDS TRIGGER
CREATE OR REPLACE TRIGGER TR_ID_PRI_WORDS BEFORE INSERT ON words FOR EACH ROW 
BEGIN SELECT ID_PRI_WORDS.NEXTVAL INTO :NEW.PK_ID FROM DUAL; END;

ALTER TRIGGER TR_ID_PRI_WORDS ENABLE;

--DELETING WORDS TRIGGER IF NEEDED
DROP TRIGGER TR_ID_PRI_WORDS;

--Testing Triggers
-- TESTING WORDS TRIGGER
INSERT INTO words (WORD) VALUES ('Abandon');












